#!/bin/bash
# Flux InstructPix2Pix Training Script
# NOTE: Flux is very new - official InstructPix2Pix training not yet available

echo "=========================================="
echo "Flux InstructPix2Pix Training"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT NOTE:"
echo ""
echo "Flux (released Aug 2024) is very new and there are"
echo "NO official InstructPix2Pix training scripts yet."
echo ""
echo "=========================================="
echo "RECOMMENDED ALTERNATIVES:"
echo "=========================================="
echo ""
echo "1. ✅ SD 1.5 (Proven, Fast: ~1.5-2 days)"
echo "   cd ../sd1_5"
echo "   ./train.sh --data_dir ./data_hf"
echo ""
echo "2. ✅ SDXL (Better Quality: ~3-5 days)"
echo "   cd ../sdxl"
echo "   ./train.sh --data_dir ./data_hf"
echo ""
echo "3. ⏰ Wait for Official Flux Scripts"
echo "   Monitor:"
echo "   - https://github.com/huggingface/diffusers"
echo "   - https://github.com/black-forest-labs/flux"
echo ""
echo "=========================================="
echo "WHY NO FLUX YET?"
echo "=========================================="
echo ""
echo "Flux uses a different architecture than SD/SDXL:"
echo "  • Flow matching (not diffusion)"
echo "  • Transformer-based (not UNet)"
echo "  • Dual text encoders (T5 + CLIP)"
echo "  • Different training objectives"
echo ""
echo "Adapting for InstructPix2Pix requires:"
echo "  1. Modifying transformer for conditional input"
echo "  2. Flow matching with image conditioning"
echo "  3. Proper handling of dual encoders"
echo "  4. Extensive testing and validation"
echo ""
echo "=========================================="
echo "CURRENT STATUS:"
echo "=========================================="
echo ""
echo "Available Flux training:"
echo "  ✅ LoRA fine-tuning (basic)"
echo "  ✅ DreamBooth (basic)"
echo "  ❌ InstructPix2Pix (not yet)"
echo "  ❌ ControlNet-style (not yet)"
echo ""
echo "=========================================="
echo "RECOMMENDATION:"
echo "=========================================="
echo ""
echo "Start with SDXL for production-ready results:"
echo ""
echo "  cd ../sdxl"
echo "  ./train.sh --data_dir ./data_hf"
echo ""
echo "SDXL offers excellent quality and is battle-tested."
echo ""
echo "=========================================="
echo ""
echo "Press Ctrl+C to exit, or Enter to see training stub..."
read

# Stub implementation
python train_instruct_pix2pix_flux.py "$@"

